baseurl = "http://quent.al/"
languageCode = "en-us"
title = "Quent.al"
theme = "beautifulhugo"

[Params]
    logo = "images/logo.jpg"

[Author]
    name = "Guilherme Quental"
    email = "guilherme@quent.al"
    facebook = "gquental"
    github = "gquental"

[permalinks]
    page = "/:title/"