baseurl = "http://quent.al/"
languageCode = "en-us"
title = "Quent.al"
theme = "beautifulhugo"
disqusShortname = "quental"
googleAnalytics = "UA-76744640-1"
publishDir = "docs"

[Params]
    logo = "images/logo.jpg"

[Author]
    name = "Guilherme Quental"
    email = "guilherme@quent.al"
    facebook = "gquental"
    github = "gquental"

[permalinks]
    page = "/:title/"
    
[blackfriday]
   plainIDAnchors = true
   hrefTargetBlank = true
